export const FETCH_CLAIMS_FAILURE = 'FETCH_CLAIMS_FAILURE';
export const FETCH_CLAIMS_REQUEST = 'FETCH_CLAIMS_REQUEST';
export const FETCH_CLAIMS_SUCCESS = 'FETCH_CLAIMS_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
